# Generated by Django 3.1.3 on 2021-06-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registraion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=150)),
                ('cname', models.CharField(max_length=30)),
                ('selection', models.CharField(blank=True, choices=[('Andhra-Pradesh', 'Andhra-Pradesh'), ('Arunachal-Pradesh', 'Arunachal-Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal-Pradesh', 'Himachal-Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya-Pradesh', 'Madhya-Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil-Nadu', 'Tamil-Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar-Pradesh', 'Uttar-Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West-Bengal', 'West-Bengal')], max_length=150, null=True)),
                ('pin', models.IntegerField()),
                ('imgup', models.ImageField(upload_to='picture')),
            ],
        ),
    ]
