# Generated by Django 3.1.3 on 2021-06-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registraion',
            name='mobile',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registraion',
            name='pin',
            field=models.CharField(max_length=6),
        ),
    ]
