# Generated by Django 3.1.3 on 2021-06-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210626_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registraion',
            name='pin',
            field=models.CharField(max_length=10),
        ),
    ]
