# Generated by Django 3.1.3 on 2021-06-27 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210626_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registraion',
            old_name='address1',
            new_name='Address1',
        ),
        migrations.RenameField(
            model_name='registraion',
            old_name='address2',
            new_name='Address2',
        ),
        migrations.RenameField(
            model_name='registraion',
            old_name='cname',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='registraion',
            old_name='mail',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='registraion',
            old_name='fname',
            new_name='First_name',
        ),
        migrations.RenameField(
            model_name='registraion',
            old_name='imgup',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='registraion',
            old_name='lname',
            new_name='Last_name',
        ),
        migrations.RenameField(
            model_name='registraion',
            old_name='mobile',
            new_name='Mobile',
        ),
        migrations.RenameField(
            model_name='registraion',
            old_name='pin',
            new_name='Pincode',
        ),
        migrations.RenameField(
            model_name='registraion',
            old_name='selection',
            new_name='State',
        ),
    ]
