# Generated by Django 3.1.3 on 2021-06-27 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20210627_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registraion',
            old_name='Image',
            new_name='Image1',
        ),
    ]
