# Generated by Django 3.1.3 on 2021-06-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20210627_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registraion',
            name='Image1',
        ),
        migrations.AddField(
            model_name='registraion',
            name='picture',
            field=models.ImageField(default='', upload_to='media/'),
            preserve_default=False,
        ),
    ]
