# Generated by Django 3.1.3 on 2021-06-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20210628_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registraion',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
